[project]
name = "mcp-kroger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kroger-api==0.2.0",
    "mcp==1.13.1",
    "python-dotenv==1.1.1",
    "requests==2.32.5",
]